load_defaults: 8.0.0
development:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solr:8983/solr/app-dev" %>
test: &test
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solr:8983/solr/app-test" %>
production:
  adapter: solr
  url: <%= ENV['SOLR_URL'] || "http://solr:8983/solr/app" %>
